Add Giveaway Functionality to the ArtBot
curatingbits/artblocksiobot pull request #40
Opened 2021-05-04 02:24 UTC by CosineXArt

Uses the node package discord-giveaways to manage random drawings on Discord.

https://github.com/Androz2091/discord-giveaways

You will need to add CHANNEL_MINTS to the .env file, and give someone the "giveaway master" role to be able to kick off giveaways.  It will silently ignore anything that doesn't start with "giveaway!<cmd>", so I think it's not likely to accidentally start an event, but we can make it more complicated if you like.

Only thing not done yet is I'd like to play with using custom Emojis, but we'd need to get those set up on the test server first.

2021-05-05 04:25 UTC, jakerockland requested changes
This is fantastic work 💯 

I've added couple requests around a bit of refactoring and adding a "help" command and then I think we should be set to push this live.

2021-05-05 04:25 UTC, jakerockland commented on index.js
> +//Manage Giveaways with Artbot
Minor thing, but can we move this new chunk of code to live after the:

```
bot.login(TOKEN);

bot.on("ready", () => {
  console.info(`Logged in as ${bot.user.tag}!`);
});
```

I think its a bit easier to visually parse this file that way.

2021-05-05 04:25 UTC, jakerockland commented on Utils/giveawayCommands.js
> +        .catch((e) => {
Nit: here and in the few places above can we use `catch((error) =>` rather than `catch((e) =>` as a pattern? It makes the code that follows a bit easier to read (and code is read more often than written).

2021-05-05 04:25 UTC, jakerockland commented on Utils/giveawayCommands.js
> +        }
This logic is duplicated in a couple places, can we please split off into its own little helper function?

2021-05-05 04:25 UTC, jakerockland commented on Utils/giveawayCommands.js
> +    if ((command === "start") || (command === "reroll") || (command === "end")) {
In addition to "start", "reroll" and "end", could we please add a "help" command that explains how to use the giveaway function? I think inevitably there will be someone who needs to be reminded, is taking over the giveaway-runner role, etc.

2021-05-05 04:25 UTC, jakerockland commented on Utils/giveawayCommands.js
> +
I think the logic within this `if (command === "start")` branch is big enough to be its own helper function.

I think we could preferably do this for each of the commands (start, reroll, end, and help), make them helpers that are internal to this file, which would allow the if-else branching here to be a bit easier to parse over and then one can dig into each helper method as needed.

2021-05-05 15:36 UTC, CosineXArt commented on index.js
> +//Manage Giveaways with Artbot
Let me test that out, I thought I had to add these items before the login command, but I'll check if that's true.

2021-05-05 15:37 UTC, CosineXArt commented on Utils/giveawayCommands.js
> +        .catch((e) => {
Sure thing!

2021-05-05 15:38 UTC, CosineXArt commented on Utils/giveawayCommands.js
> +
Good point, will do.

2021-05-05 15:38 UTC, CosineXArt commented on Utils/giveawayCommands.js
> +    if ((command === "start") || (command === "reroll") || (command === "end")) {
Excellent point, I'll add that.

2021-05-05 15:38 UTC, CosineXArt commented on Utils/giveawayCommands.js
> +        }
Sure.

2021-05-06 03:10 UTC, CosineXArt commented on index.js
> +//Manage Giveaways with Artbot
Looks like I can do it this way.

2021-05-06 03:10 UTC, CosineXArt commented
All your comments should be addressed with this latest commit.

2021-05-06 15:16 UTC, jakerockland commented on Utils/giveawayCommands.js
> +}
One minor nit here: somewhat of a style preference, I think its a bit easier to read if this branching uses if-else rather than 4 if statements as it providers a better guarantee to the reader that only one of these may be executed per command.

2021-05-06 15:17 UTC, jakerockland reviewed
Just one minor thing here that would be nice if you can tweak. Non-blocking though if its a hassle.

I'll merge and push this tonight :) looks great!! Thank you.

2021-05-07 01:16 UTC, jakerockland approved these changes
Looks great, thank you!! 😄

2021-05-07 01:16 UTC, merged