first draft of factory bot
curatingbits/artblocksiobot pull request #54
Opened 2021-07-25 03:15 UTC by CosineXArt

This is a draft.  Code's still a little messy, but it now covers the main cases, handles projects that aren't completely minted, and refreshes the metadata on an interval.  (It takes less than a minute on average to refresh, and updates incrementally, so it shouldn't be noticeable by the user).

Add the following two .env variables to make it work:
CHANNEL_FACTORY
METADATA_REFRESH_INTERVAL_MINUTES

2021-08-05 07:14 UTC, jakerockland commented on Utils/parseArtBlocksAPI.js
> +        return platform.projects_list;
Nit: Can you fix alignment of this return statement please?

2021-08-05 07:33 UTC, jakerockland requested changes
This generally looks really really great! A couple minor nits that are appreciated and not necessary as well as some various minor questions 💯 Thank you @CosineXArt 🙏

2021-08-05 07:33 UTC, jakerockland commented on Utils/parseArtBlocksAPI.js
> +        return project;
Nit: Can you fix alignment of this return statement please?

2021-08-05 07:33 UTC, jakerockland commented on Utils/parseArtBlocksAPI.js
> +        return platform.projects_list;
Nit: Can you fix alignment of this return statement please?

2021-08-05 07:33 UTC, jakerockland commented on Utils/parseArtBlocksAPI.js
> +    }
Could you add a comment please explaining why this needs to be done?

2021-08-05 07:33 UTC, jakerockland commented on Utils/parseArtBlocksAPI.js
> +        project.token_ids.push(id * 1000000 + i);
We should probably define 1000000 as a constant at the top of the file here, this seems easy to typo if someone was modifying this in the future. 

Also reminds that that I should do some minor refactoring of the ProjectBot class in the future, though that is clearly out of scope here for this PR.

2021-08-05 07:33 UTC, jakerockland commented on Utils/parseArtBlocksAPI.js
> +           const response = await fetch(`https://api.artblocks.io/token/${tokenid}`, { timeout: 5000 });
We probably should be using timeouts in our other fetches like you are here, but curious why you explicitly added the timeout (were you seeing odd behavior without it)?

2021-08-05 07:33 UTC, jakerockland commented on Utils/parseArtBlocksAPI.js
> +       let tokenid = id*1000000;
Nit: I think tokenID is slightly more readable.

2021-08-05 07:33 UTC, jakerockland commented on Utils/parseArtBlocksAPI.js
> +       let is_factory = false;
Nit: generally we're using camelCase elsewhere, could we keep that the case here with is_factory->isFactory?

2021-08-05 07:33 UTC, jakerockland commented on Classes/FactoryBot.js
> +const MINT_ADDRESS = "0x0000000000000000000000000000000000000000";
Is this MINT_ADDRESS needed or a reference that has since been cleaned up?

2021-08-05 07:33 UTC, jakerockland commented on Classes/FactoryBot.js
> +const UNKNOWN_USERNAME = "unknown";
Similarly, are these needed?

2021-08-05 07:33 UTC, jakerockland commented on Classes/FactoryBot.js
> +const METADATA_REFRESH = process.env.METADATA_REFRESH_INTERVAL_MINUTES;
What do you think an appropriate value is here? My inclination would be to start with something like 3 hours or 6 hours and work down from there if needed at all? Perhaps we could do less though, like 1 hour. There aren't that many API calls involved.

2021-08-05 07:33 UTC, jakerockland commented on Classes/FactoryBot.js
> +                   );
Love that we can do this. 💜🙏

2021-08-05 07:33 UTC, jakerockland commented on Classes/FactoryBot.js
> +    let detailsRequested = content.toLowerCase().includes("detail");
Do we need to pull this out as a var?

2021-08-05 07:33 UTC, jakerockland commented on Classes/FactoryBot.js
> +let factoryBotList = [];
Would be nice to have a small comment explaining what gets stored in this variable (that it is a place in memory for the project handler classes to live).

2021-08-05 07:33 UTC, jakerockland commented on Classes/FactoryBot.js
> +    }
Nit: we could probably factor out `factoryBotList[nameIndex]` to simplify a bit here.

2021-08-07 02:35 UTC, CosineXArt commented on Utils/parseArtBlocksAPI.js
> +        return project;
absolutely

2021-08-07 02:41 UTC, CosineXArt commented on Utils/parseArtBlocksAPI.js
> +        project.token_ids.push(id * 1000000 + i);
done, although I wonder if it would be easier to just change this to 1e6 to avoid the typo problem.

2021-08-07 02:51 UTC, CosineXArt commented on Utils/parseArtBlocksAPI.js
> +           const response = await fetch(`https://api.artblocks.io/token/${tokenid}`, { timeout: 5000 });
Yes, if you hit the ArtBlocks API with ~3-400 requests a few of them fail, and without the timeout, thing error unpredictably (closed sockets, etc.).  But now that you point this out, I need a timeout on my fetches of the project and platform endpoints as well.

2021-08-07 02:52 UTC, CosineXArt commented on Utils/parseArtBlocksAPI.js
> +    }
I think this was a copy paste error, and I don't think we need it.  Deleted.

2021-08-07 02:52 UTC, CosineXArt commented on Classes/FactoryBot.js
> +const METADATA_REFRESH = process.env.METADATA_REFRESH_INTERVAL_MINUTES;
I ran it for a while on 5 minute refreshes in test, and it was fine.  It takes a minute or so to complete the refresh, so 1 hour would probably be fine.

2021-08-07 02:54 UTC, CosineXArt commented on Classes/FactoryBot.js
> +                   );
LOL, we finally fix the problem of the randomizer and unfinished mints, and now we don't have any more uncompleted projects.  At least you can #? squiggles!

2021-08-07 02:55 UTC, CosineXArt commented on Classes/FactoryBot.js
> +    let detailsRequested = content.toLowerCase().includes("detail");
nope.  Accidental copy/paste error from the ProjectBot class.

2021-08-07 02:55 UTC, CosineXArt commented on Classes/FactoryBot.js
> +let factoryBotList = [];
I can add one.

2021-08-07 03:00 UTC, CosineXArt commented on Classes/FactoryBot.js
> +    }
sure thing.

2021-08-09 16:06 UTC, jakerockland commented on Classes/FactoryBot.js
> +const METADATA_REFRESH = process.env.METADATA_REFRESH_INTERVAL_MINUTES;
Rad, that sounds good to me! Would you mind adding a comment to this effect?

2021-08-09 16:07 UTC, jakerockland commented on Utils/parseArtBlocksAPI.js
> +           const response = await fetch(`https://api.artblocks.io/token/${tokenid}`, { timeout: 5000 });
Aha, thanks for clarifying :) If you don't mind, could you add a comment to this effect?

2021-08-11 04:02 UTC, jakerockland approved these changes
This looks great! Great work and thank you for doing this. 💜🙏

2021-08-11 04:02 UTC, merged